; Réglages prod.
memory_limit = 256M
max_execution_time = 30

display_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED

opcache.enable = 1
opcache.validate_timestamps = 0
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000
opcache.interned_strings_buffer = 16
opcache.preload = /app/config/preload.php
opcache.preload_user = root

realpath_cache_size = 4096K
realpath_cache_ttl = 600

date.timezone = UTC
