framework:
    router:
        # Sert à générer des URL hors contexte HTTP, en commande console.
        default_uri: '%env(DEFAULT_URI)%'

when@prod:
    framework:
        router:
            strict_requirements: null
