<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * La table d'outbox de Messenger.
 *
 * Elle est ici, versionnée et relue, plutôt que créée au vol par `auto_setup` : une
 * table que le framework fabrique tout seul au premier message est une table dont
 * personne ne connaît le schéma, et qui apparaît en production au pire moment.
 *
 * Le schéma vient du transport lui-même (`doctrine:migrations:diff` le connaît, le
 * transport déclarant sa table au schéma Doctrine) — d'où les noms et l'index hashé,
 * qu'il ne faut pas « embellir » : le diff les compare tels quels.
 *
 * Pas de trigger PostgreSQL à créer : cette version du transport émet le `pg_notify`
 * depuis PHP à l'envoi, et le worker écoute le canal. Le `LISTEN/NOTIFY` évite au
 * worker de sonder la table en boucle.
 */
final class Version20260810170705 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Shared : table messenger_messages (outbox)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
    }
}
